# Generated by Django 3.2.5 on 2022-01-06 22:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('f_name', models.CharField(max_length=200)),
                ('l_name', models.CharField(max_length=200)),
                ('log', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Heartrate_Model',
            fields=[
                ('sex', models.IntegerField()),
                ('anaemia', models.IntegerField()),
                ('creatinine_phosphokinase', models.IntegerField()),
                ('diabetes', models.IntegerField()),
                ('ejection_fraction', models.IntegerField()),
                ('high_blood_pressure', models.IntegerField()),
                ('platelets', models.IntegerField()),
                ('serum_creatinine', models.IntegerField()),
                ('serum_sodium', models.IntegerField()),
                ('smoking', models.IntegerField()),
                ('time', models.IntegerField()),
                ('log', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
