# Generated by Django 3.2.5 on 2022-01-06 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='model',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='rate.heartrate_model'),
            preserve_default=False,
        ),
    ]
