# Generated by Django 3.2.5 on 2022-01-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_details_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='model',
        ),
        migrations.AddField(
            model_name='details',
            name='model',
            field=models.ManyToManyField(to='rate.Heartrate_Model'),
        ),
    ]
