# Generated by Django 3.2.5 on 2022-01-10 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rate', '0006_details_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='age',
        ),
        migrations.RemoveField(
            model_name='details',
            name='anaemia',
        ),
        migrations.RemoveField(
            model_name='details',
            name='creatinine_phosphokinase',
        ),
        migrations.RemoveField(
            model_name='details',
            name='diabetes',
        ),
        migrations.RemoveField(
            model_name='details',
            name='ejection_fraction',
        ),
        migrations.RemoveField(
            model_name='details',
            name='high_blood_pressure',
        ),
        migrations.RemoveField(
            model_name='details',
            name='platelets',
        ),
        migrations.RemoveField(
            model_name='details',
            name='serum_creatinine',
        ),
        migrations.RemoveField(
            model_name='details',
            name='serum_sodium',
        ),
        migrations.RemoveField(
            model_name='details',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='details',
            name='smoking',
        ),
        migrations.RemoveField(
            model_name='details',
            name='time',
        ),
        migrations.AddField(
            model_name='details',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
