# Generated by Django 3.2.5 on 2022-01-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_auto_20220106_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='model',
        ),
        migrations.AddField(
            model_name='details',
            name='anaemia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='creatinine_phosphokinase',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='diabetes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='ejection_fraction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='high_blood_pressure',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='platelets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='serum_creatinine',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='serum_sodium',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='sex',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='smoking',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='details',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Heartrate_Model',
        ),
    ]
